version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "15:45"
  # Maintian npm dependencies
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "16:00"
    open-pull-requests-limit: 10
